version: '3'

services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/certbot/conf:/etc/letsencrypt
    - ./nginx/certbot/logs:/var/log/letsencrypt
    - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
    - 80:80
    - 443:443
